### ISSUE TITLE
feature: 書籍情報取得関連のAPIについて

### ISSUE THREAD

**Issue by taba2424** [calmato/gran-book#306]
## 変更内容

* [2021/06/17時点のAPIのSwagger](https://github.com/calmato/gran-book/files/6670136/_apiv1.yaml.zip)
* [変更案のSwagger](https://github.com/calmato/gran-book/files/6670203/_apiv1-1.yaml.zip)

## 変更箇所について

* 本棚の書籍情報取得API (`/v1/users/{userId}/books/{bookId}`) のレスポンスを以下内容へ変更
  * 2021/06/17時点の 書籍情報取得API (`/v1/books/{bookId}`) のレスポンスの内容に合わせる
  * -> 追加で、 自分が登録した `読んだ日` , `感想` の情報を bookshelf に含まれるように

* 書籍情報取得API (`/v1/books/{bookId}`) のレスポンスから ユーザ固有の情報 `bookshelf` を削除
* 書籍情報取得API (`/v1/books/{bookId}`) のレスポンスへ 本のレビュー一覧 (たぶん50件ほど) を追加

* (Swaggerではかけんかったんだけど、) 本棚の書籍情報取得API (`/v1/users/{userId}/books/{bookId}`) で、まだ本棚に追加してないユーザについて、 bookshelf のことは undefined で返すようにしようと思ってる。

---

## 変更後のSwaggerのスクリーンショット

* 書籍情報取得API (`/v1/books/{bookId}`)
  ![スクリーンショット 2021-06-17 21 38 39](https://user-images.githubusercontent.com/27718413/122398212-a25d0480-cfb4-11eb-9a57-b2c5cdfa181d.png)

* 本棚の書籍情報取得API (`/v1/users/{userId}/books/{bookId}`)
  ![スクリーンショット 2021-06-17 21 38 56](https://user-images.githubusercontent.com/27718413/122398224-a557f500-cfb4-11eb-9374-776bcece9ea9.png)

**Comment by taba2424** [comment]
@wf-yamaday 

詳細は、添付のzipファイルをご覧いただければと🙇‍♂️
これでよければ、来週末までにAPIの修正かけたいなと

**Comment by wf-yamaday** [comment]
@taba2424 確認します🙏

**Comment by wf-yamaday** [comment]
API仕様書作成ありがとう🙏

ユースケースと対応させながら確認させて欲しい🙇‍♂️

## 1. ユーザーの本棚にある書籍一覧を取得（nativeでの初期描画）

`/v1/users/{userId}/books` にアクセスし書籍情報を取得
レスポンスは以下の形式で`bookshelf`プロパティを見て各書籍がどの本棚に配置されているか確認する。

```
"books": [
    {
      "id": 0,
      "title": "string",
      "titleKana": "string",
      "description": "string",
      "isbn": "string",
      "publisher": "string",
      "publishedOn": "string",
      "thumbnailUrl": "string",
      "rakutenUrl": "string",
      "size": "string",
      "author": "string",
      "authorKana": "string",
      "createdAt": "string",
      "updatedAt": "string",
      "bookshelf": {
        "id": 0,
        "status": "string",
        "readOn": "string",
        "impression": "string",
        "createdAt": "string",
        "updatedAt": "string"
      }
    }
  ],
```

## 2. ユーザーが自分の書籍の選択し詳細を確認

選択した書籍のIDを利用して`/v1/books/{bookId}`にアクセスしレビュー情報を含めた書籍情報を取得。
レスポンスは以下の形式で`reviews`プロパティには該当書籍の全てのレビューが含まれている。


```
{
  "id": 0,
  "title": "string",
  "titleKana": "string",
  "description": "string",
  "isbn": "string",
  "publisher": "string",
  "publishedOn": "string",
  "thumbnailUrl": "string",
  "rakutenUrl": "string",
  "size": "string",
  "author": "string",
  "authorKana": "string",
  "createdAt": "string",
  "updatedAt": "string",
  "reviews": [
    {
      "id": 0,
      "impression": "string",
      "createdAt": "string",
      "updatedAt": "string",
      "user": {
        "id": "string",
        "username": "string",
        "thumbnailUrl": "string"
      }
    }
  ],
  "limit": 0,
  "offset": 0,
  "total": 0
}
```

<hr />

ここまでの認識で合ってる？？
個人的には2の場合にレビューが全て取得できるなら、特定の書籍のレビューを全件取得する`/v1/books/{bookId}/reviews`のエンドポイントの使い道がいまいちわかっていない…

**Comment by taba2424** [comment]
@wf-yamaday 

> ここまでの認識で合ってる？？
> 個人的には2の場合にレビューが全て取得できるなら、特定の書籍のレビューを全件取得する/v1/books/{bookId}/reviewsのエンドポイントの使い道がいまいちわかっていない…

1の認識は合ってる!!
2は上に書いてるように、50件ぐらいを上限にレビュー一覧を返すようにするのどうかなと考えてる。
(仮にレビューが1000件とか5000件とかなった時のこと考えると、どっかで上限持たせないと処理できなくなりそうだなと思い。で、とりあえず50件って数字にしてる)
-> なので、それ以上の件数を取得したい時とかにレビュー一覧API叩きに行く感じにすればいいのかなと

**Comment by taba2424** [comment]
* [x] 本棚の書籍情報取得API (/v1/users/{userId}/books/{bookId}) のレスポンスを変更
    * -> bookshelfオブジェクト内に `reviewId` を追加
    * -> レビュー一覧も取得できるようにレスポンスへ追加 (デフォルト: Max 100件)
    * https://github.com/calmato/gran-book/pull/326
    * https://github.com/calmato/gran-book/pull/327
* [x] 本棚の書籍情報一覧取得API (/v1/users/{userId}/books) のレスポンスを変更
    * -> bookshelfオブジェクト内に `reviewId` を追加
    * https://github.com/calmato/gran-book/pull/326
    * https://github.com/calmato/gran-book/pull/327
* [ ] 書籍情報取得API (/v1/books/{bookId}) のレスポンスから ユーザ固有の情報 bookshelf を削除
* [ ] 書籍情報取得API (/v1/books/{bookId}) のレスポンスへ 本のレビュー一覧 (たぶん50件ほど) を追加

**Comment by taba2424** [comment]
@wf-yamaday 
↑に進捗載せるようにする

**Comment by taba2424** [comment]
対応済みのためクローズ
